#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: f35655a
#
Name     : qpl
Version  : 1.6.0
Release  : 2
URL      : https://github.com/intel/qpl/archive/refs/tags/v1.6.0.tar.gz
Source0  : https://github.com/intel/qpl/archive/refs/tags/v1.6.0.tar.gz
Summary  : @CMAKE_PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : MIT
Requires: qpl-data = %{version}-%{release}
Requires: qpl-lib = %{version}-%{release}
Requires: qpl-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : googletest-dev
BuildRequires : nasm
BuildRequires : util-linux-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!--
SPDX-License-Identifier: MIT
-->
Intel® Query Processing Library (Intel® QPL)
============================================

%package data
Summary: data components for the qpl package.
Group: Data

%description data
data components for the qpl package.


%package dev
Summary: dev components for the qpl package.
Group: Development
Requires: qpl-lib = %{version}-%{release}
Requires: qpl-data = %{version}-%{release}
Provides: qpl-devel = %{version}-%{release}
Requires: qpl = %{version}-%{release}

%description dev
dev components for the qpl package.


%package lib
Summary: lib components for the qpl package.
Group: Libraries
Requires: qpl-data = %{version}-%{release}
Requires: qpl-license = %{version}-%{release}

%description lib
lib components for the qpl package.


%package license
Summary: license components for the qpl package.
Group: Default

%description license
license components for the qpl package.


%prep
%setup -q -n qpl-1.6.0
cd %{_builddir}/qpl-1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725549120
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQPL_BUILD_TESTS=OFF \
-DQPL_BUILD_EXAMPLES=OFF \
-DQPL_LIBRARY_TYPE=SHARED  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1725549120
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qpl
cp %{_builddir}/qpl-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/qpl/f08440c426d0e6a457ae51d427f1b07b4b83bb86 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/QPL/configs/1n1d1e1w-s-n1.conf
/usr/share/QPL/configs/1n1d1e1w-s-n2.conf
/usr/share/QPL/configs/1n1d8e1w-s-n1.conf
/usr/share/QPL/configs/1n1d8e1w-s-n2.conf
/usr/share/QPL/configs/1n2d8e1w-s-n1.conf
/usr/share/QPL/configs/1n2d8e1w-s-n2.conf
/usr/share/QPL/configs/1n3d8e1w-s-n1.conf
/usr/share/QPL/configs/1n3d8e1w-s-n2.conf
/usr/share/QPL/configs/1n4d1e1w-s-n1.conf
/usr/share/QPL/configs/1n4d1e1w-s-n2.conf
/usr/share/QPL/configs/1n4d8e1w-s-n1.conf
/usr/share/QPL/configs/1n4d8e1w-s-n2.conf
/usr/share/QPL/configs/2n1d1e1w-s.conf
/usr/share/QPL/configs/2n1d8e1w-s.conf
/usr/share/QPL/configs/2n2d8e1w-s.conf
/usr/share/QPL/configs/2n3d8e1w-s.conf
/usr/share/QPL/configs/2n4d8e1w-s.conf
/usr/share/QPL/scripts/accel_conf.py
/usr/share/QPL/scripts/accel_conf.sh

%files dev
%defattr(-,root,root,-)
/usr/include/qpl/c_api/defs.h
/usr/include/qpl/c_api/dictionary.h
/usr/include/qpl/c_api/huffman_table.h
/usr/include/qpl/c_api/index_table.h
/usr/include/qpl/c_api/job.h
/usr/include/qpl/c_api/serialization.h
/usr/include/qpl/c_api/statistics.h
/usr/include/qpl/c_api/status.h
/usr/include/qpl/c_api/triplet.h
/usr/include/qpl/c_api/version.h
/usr/include/qpl/qpl.h
/usr/lib64/cmake/QPL/QPLConfig.cmake
/usr/lib64/cmake/QPL/QPLConfigVersion.cmake
/usr/lib64/cmake/QPL/QPLTargets-relwithdebinfo.cmake
/usr/lib64/cmake/QPL/QPLTargets.cmake
/usr/lib64/libqpl.so
/usr/lib64/pkgconfig/qpl.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqpl.so.1
/usr/lib64/libqpl.so.1.6.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qpl/f08440c426d0e6a457ae51d427f1b07b4b83bb86
